name: Formatting with black

on:
  push:
    paths:
      - '*.py'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable