# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing with Normal Report

on:
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7 ]
        poetry-version: [ 1.1.12 ]
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install
          poetry run playwright install
      - name: Run tests
        run: |
          poetry run pytest tests/ --junit-xml results/pytest.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Report            # Name of the check run which will be created
          path: results/pytest.xml    # Path to test results
          reporter: java-junit        # Format of test results