# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing with Normal Report

on:
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/cache@v2
        id: poetry_cache_id
        with:
          path: /Users/runner/Library/Caches/
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.12
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          poetry install
          poetry run playwright install
      - name: Run tests
        run: |
          cd tests
          chmod u+x ./test_runner.command
          poetry run sh ./test_runner.command
        continue-on-error: true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Report           # Name of the check run which will be created
          path: results/*.xml    # Path to test results
          reporter: java-junit        # Format of test results