# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing with Normal Report

on:
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.7 ]
        poetry-version: [ 1.1.12 ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install
          poetry run playwright install
      # - name: Run tests
      #   run: |
      #     cd tests
      #     chmod u+x ./test_runner.command
      #     poetry run pytest test_google.py --junitxml=../results/result_google.xml
      #     poetry run pytest test_yahoo.py --junitxml=../results/result_yahoo.xml
      - name: Run tests
        run: |
          cd tests
          chmod u+x ./test_runner.command
          poetry run sh ./test_runner.command
        continue-on-error: true
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Test Report           # Name of the check run which will be created
          path: results/*.xml    # Path to test results
          reporter: java-junit        # Format of test results